### ISSUE TITLE
Question on igrill encryption keys

### ISSUE THREAD

**Issue by davisp** [kvantetore/igrill#1]
Where did you get the encryption key here:

https://github.com/kvantetore/igrill/blob/713f4cb058cfff0807c7507541468b7c463dd3ca/igrill.py#L144

Is that something that comes out of bonding with bluetoothctl or something you managed to find elsewhere? I've got an iGrill2 I'm trying to toy around with but reading your code the step of finding that key is non-obvious.

**Comment by kvantetore** [comment]
Decompiling the android app :)

There are no attempts on obfuscating the binary, and any apk-decompiler will do. The keys for all the iDevices are neatly listed in the decompiled source.

**Comment by davisp** [comment]
Just got back to this and its exactly as you said. Thanks for the tip!

**Comment by davisp** [comment]
Just a follow up. I wanted to thank you for getting me pointed in the right direction. Between your hints and lots of banging around on python libs bluetooth on OS X I finally managed to get this working in virtualbox based on your examples.

**Comment by kvantetore** [comment]
Awesome. Apart from providing us with a fun and easy reverse engineering project, I cannot possibly fathom why idevices would go to such lengths to keep my steak temperature secret. Perhaps they are trying to protect me from neighbours knocking at my door at just the right moment? :p

**Comment by brettroyer** [comment]
Maybe one of you guys can give me a hand here.  I've got an igrill2 I'm trying to use with this library using an raspberry pi.  Following the instructions above,  I did decompile the idevices's app apk file I found in the web and did find the .plist files under the assets/device/igrill_bundle directory.  Although I can sorta follow along were you found the UUID's for firmware, etc.  I still can't figure out how you determined the encryption key.  Please point me in the right direction.  
Note:  using the Pi,  I am able to see the igrill to and obtain its MAC address.  I did plug that into the library.
