### ISSUE TITLE
iGrill V2 - Measurements

### ISSUE THREAD

**Issue by bjoernhoefer** [kvantetore/igrill#4]
Hi,

I've been very noisy on this project-issue page in the last few hours...

So far I'm now able to connect my Raspberry Pi to my iGrill V2 (with some startup-problems).

My last problem is now that it seems, that the values are read wrong (I'm always getting a temperature of 202 or 190 something) - which is even in imperal-system crap... ;-)

Can you provide me some hints, how you identified the data-fields for your iGrill mini?

Thanks

**Comment by ghost** [comment]
What version of bluez did you end up using to get this working?

Are you using the following and what steps did you follow to get things going?

1 bluepy==0.9.11 
2 pycrypto==2.6.1 
3 kavntetore's main fork?
4 main.py (what updates?)

My setup is a Raspberry Pi3 (integrated Bluetooth) and iGrillV2

I don't seem to have much luck getting to any of the handles that require authentication.  Perhaps something to do with bonding.  I'm able to pair and get battery info using bluetoothctl and gatttools but no luck replicating the iGrill specific device authorization that I see in wireshark with the AES encryption that is in the python code.

**Comment by ghost** [comment]
[iGrillV2 Wireshark Dump with Pairing and Bonding.xlsx](https://github.com/kvantetore/igrill/files/916662/iGrillV2.Wireshark.Dump.with.Pairing.and.Bonding.xlsx)

**Comment by bjoernhoefer** [comment]
Hi, so far I've also got myself a raspberry pi3 - created an sd - installed all libraries and so on.

Finally I'm ending up with the following message:
  ```
Creating Scanner
Connecting to InfluxDB server
Scanning...
Authenticating...
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    scanner.scan(30)`
File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 632, in scan`
  self.process(timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 621, in process
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData)
  File "/usr/src/igrill-master/scan.py", line 10, in handleDiscovery
    handler.handleDiscovery(scanEntry, isNewDev, isNewData)
  File "/usr/src/igrill-master/igrill.py", line 43, in handleDiscovery
    dev = IGrillMiniPeripheral(scanEntry.addr)
  File "/usr/src/igrill-master/igrill.py", line 147, in __init__
    IDevicePeripheral.__init__(self, address)
  File "/usr/src/igrill-master/igrill.py", line 92, in __init__
    if not self.authenticate():
  File "/usr/src/igrill-master/igrill.py", line 114, in authenticate
    self.characteristic(UUIDS.APP_CHALLENGE).write(challenge, True)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 148, in write
    self.peripheral.writeCharacteristic(self.valHandle, val, withResponse)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 459, in writeCharacteristic
    return self._getResp('wr')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 334, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 296, in _waitResp
    raise BTLEException(BTLEException.COMM_ERROR, "Error from Bluetooth stack (%s)" % errcode)
bluepy.btle.BTLEException: Error from Bluetooth stack (comerr)`
```

When I'm running hcidump on an shell - when main.py is "crashing" I'll see the follwing

  ```
....lots of other crap
2017-04-12 19:36:10.229837 > ACL data: handle 64 flags 0x02 dlen 9
    ATT: Error (0x01)
      Error: Attribute not found (10)
      Read By Type req (0x08) on handle 0x0052
2017-04-12 19:36:10.237729 < ACL data: handle 64 flags 0x00 dlen 23
    ATT: Write req (0x12)
      handle 0x0024 value  0x57 0xbf 0xa0 0x4f 0x61 0xba 0xad 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
2017-04-12 19:36:10.297478 > HCI Event: Number of Completed Packets (0x13) plen 5
    handle 64 packets 2
**2017-04-12 19:36:10.364835 > ACL data: handle 64 flags 0x02 dlen 9
    ATT: Error (0x01)
      Error: Insufficient authentication (5)
      Write req (0x12) on handle 0x0024**
2017-04-12 19:36:12.436949 < HCI Command: Disconnect (0x01|0x0006) plen 3
    handle 64 reason 0x13
    Reason: Remote User Terminated Connection
2017-04-12 19:36:12.437512 > HCI Event: Command Status (0x0f) plen 4
    Disconnect (0x01|0x0006) status 0x00 ncmd 1
2017-04-12 19:36:12.457885 > HCI Event: Disconn Complete (0x05) plen 4
    status 0x00 handle 64 reason 0x16
    Reason: Connection Terminated by Local Host
  ```

Maybe the V2 has another key... maybe I can find it in the android app... or an bluetooth dump from my smartphone - I'm not very skilled in bluetooth debugging - maybe the key is transmitted in "plaintext" - which would be tooooooo nice....

Regarding the changes: see -> [The other case](https://github.com/kvantetore/igrill/issues/2)

System is all updated so far - so bluez is 5.23-2+rpi2

What I've installed:
  ```
apt-get install python-pip libglib2.0-dev
pip install bluepy
apt-get install python-crypto
pip install influxdb
apt-get install bluez-hcidump
  ```

PS: Please provide wireshark files in pcap format - excel is so bad from the security and information perspective ;-)

**Comment by ghost** [comment]
From onlywade's fork:

    # encryption key for the iGrill v2

    encryption_key = [-33, 51, -32, -119, -12, 72, 78, 115, -110, -44, -49, -71, 70, -25, -123, -74]

I did confirm this with some sample runs of known APP challenges and Device responses and the py code for encryption.

I'll post the wireshark pcap when I can find the correct file. :)

**Comment by ghost** [comment]
I'm assuming you updated the bluetooth device address D4:81:CA:**21:2E:2F** in the code? The last half of the address will be different for each iGrill device found on a sticker on the PCB if you remove the front cover.

**Comment by bjoernhoefer** [comment]
Yes, of course found mine with bluetooth-scanner...

I've also "found" the encryption keys in the Weber-App 

```
encryption_key = [39, 98, -4, 94, -54, 19, 69, -27, -99, 17, -34, -74, -10, -13, -116, 28] - iGrill V3
encryption_key = [-33, 51, -32, -119, -12, 72, 78, 115, -110, -44, -49, -71, 70, -25, -123, -74] - iGrill V2 
    # encryption_key = [-19, 94, 48, -114, -117, -52, -111, 19, 48, 108, -44, 104, 84, 21, 62, -35] - iGrill Mini
```


I also ran into the problem when It tries to connect I'll get:

```
Traceback (most recent call last):
  File "/usr/src/igrill-master/main.py", line 41, in <module>
    scanner.scan(30)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 632, in scan
    self.process(timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 621, in process
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData)
  File "/usr/src/igrill-master/scan.py", line 10, in handleDiscovery
    handler.handleDiscovery(scanEntry, isNewDev, isNewData)
  File "/usr/src/igrill-master/igrill.py", line 43, in handleDiscovery
    dev = IGrillMiniPeripheral(scanEntry.addr)
  File "/usr/src/igrill-master/igrill.py", line 149, in __init__
    IDevicePeripheral.__init__(self, address)
  File "/usr/src/igrill-master/igrill.py", line 82, in __init__
    btle.Peripheral.__init__(self, address)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 318, in __init__
    self.connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 367, in connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral d4:81:ca:23:67:a1, addr type: public
```


Currently I'm stucked - but I think maybe they'Ve changed the methode how the encryption key is "calculated" - as I'm currently a bit short in time - I maybe find a few moments where I can take a look in the extracted android app.... 

Maybe @kvantetore can provide me/us the source where he found it in the app.... ;-)


Cheers

**Comment by ghost** [comment]
Did you try any of the other forks to see if you could get those working?  Also, I noticed a comment about pairing/bonding outside of the igrill application.  Are you pairing up via the bt icon in the taskbar in desktop mode?

**Comment by bjoernhoefer** [comment]
Yes, tried it with the forks - ended up with the same error... that's why I was thinking about the changed method of creating the encryption key....

**Comment by ghost** [comment]
Would be nice if someone posted steps to actually get some temp readings from the iGrill V2.  Here is the wireshark dump that I collected.  I first went into settings on my iPad and forgot the iGrill device so it would log all the pairing and bonding stuff and make use of the encryption keys to show the encrypted traffic.  I then went into the Webber app and connected the device.  Some valuable info on the actual handles used and the transfer of keys for authorization. Let me know if this helps.

Remove the txt extention.

[iGrillV2 with pairing and bonding.pcap.txt](https://github.com/kvantetore/igrill/files/924347/iGrillV2.with.pairing.and.bonding.pcap.txt)

**Comment by bjoernhoefer** [comment]
Hi,

I've invested some time to stick together some code-parts, which does the essential work...
```
import bluepy.btle as btle
import random

encryption_key = [-33, 51, -32, -119, -12, 72, 78, 115, -110, -44, -49, -71, 70, -25, -123, -74]

address = "12:34:56:78:90:12"

igrill = btle.Peripheral(address)
print "Attached"

igrill.setSecurityLevel("medium")
print "raised security level"

for charas in igrill.getCharacteristics() :
 print charas

key = "".join([chr((256 + x) % 256) for x in encryption_key])
challenge = str(bytearray([(random.randint(0, 255)) for i in range(8)] + [0] * 8))

app_uuid = igrill.getCharacteristics(uuid="64ac0002-4a4b-4b58-9f37-94d3c52ffdf7")[0]
app_uuid.write(challenge, True)
```

This code connects to the device with the mac-addrese and prints out the "characteristics" of the device (the UUID, which you find in the igrill.py).

If you enter the MAC of your iGrillv2 and run the script you will get an error:
```
Traceback (most recent call last):
  File "connect.py", line 22, in <module>
    app_uuid.write(challenge, True)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 148, in write
    self.peripheral.writeCharacteristic(self.valHandle, val, withResponse)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 459, in writeCharacteristic
    return self._getResp('wr')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 334, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 296, in _waitResp
    raise BTLEException(BTLEException.COMM_ERROR, "Error from Bluetooth stack (%s)" % errcode)
bluepy.btle.BTLEException: Error from Bluetooth stack (comerr)
```

As the error comes from bluepy - i think this should be the next station to investigate....
I read some issues in bluepy where the almost have the same errors, where they tried to write to some characteristics which were not writeable... but as it was 4 in the morning, I could have missunderstood that also... 

I will take a look at the pcap, maybe I can find some information, to which characteristic what values are send... but I'll take care about that later...

**Comment by ghost** [comment]
I think you should look at the pcap file.  Handle 0x0024 is the UUID you are writing to and it also fails to write on line 337 due to insufficient authentication.  The Webber app appears to then pair/bond then the writes to handle 0x0024 seem to work on line 733.  You can see the value as 5f4a7f27c6bf2e740000000000000000 with the first 8 hex values randomly selected.  So something between 337 and 733 doesn't seem to be working correctly and we are never allowed to write to that handle.  Are you familiar with bluetoothctl or gatttool?  I've also tried them just to figure out the sequencing but I never seem to be able to write to handle 0x0024.  Prob something simple...  How are you doing the pairing/bonding?  Is that part of the bluepy python code or do you do that on the pi desktop?

**Comment by bjoernhoefer** [comment]
Solution found...

As this solution completely differs from this approach - I've created my own project... 

https://github.com/bjoernhoefer/iGrill_bbqmqtt/tree/master


The solution came to me mind when I found out that the problem with the code above was that the read-request is not authenticate (error popped up when doing a hcidump).

Then I tried to recreate it with gatttool - and got the message again (not authenticated) - so I think maybe the V2 has a changed "logon-schema".

While thinking and googleing about such stuff I noticed that gatttool got some "information" sent form the V2 itself... 

Taking a look at the new "information" I found out that the V2 is sending the probe-temperature to the connected bluetooth device...

Thats my solution now - I'm just connecting and waiting for updates which are send to me from the iGrill v2...

No possibility to change settings, or poll information in an self-defined rythm - but I'm good with that, that I'm getting at least this information...

Maybe I can get the battery-information or other stuff also - but for now, I'm f**king happy that I did not spend money on the "wrong" device... 

In my "solution" I've also added mqtt-support which is nice, as most home-automation systems now support mqtt...

So, sorry for double adevertising on my solution - but you can find it here: https://github.com/bjoernhoefer/iGrill_bbqmqtt/tree/master
:-)

So, its almost 5 in the morning here, I think I deserve some sleep now... 

Cheers!

PS: Answers to your questions:
You're right the authentication does not work as it is in the code here - maybe something special of the V2 - or maybe in this firmware.... Also I can't really see much in your pcap file as wireshark does'nt interpret them correct...
Yes, I know hcitool and gatttool now - 3-5 days ago I didn't ;-)
parining and bonding is done by "the code" - for instance `igrill = btle.Peripheral(address)` connects the device (http://ianharvey.github.io/bluepy-doc/index.html - very much good information, sometimes/often very frustrating... I've been there the last two days, veeeery often and looooong)

**Comment by ghost** [comment]
Ok something's off here.  You are looking at handles 52,57,62 and 67 which you say represent probes 1,2,3 and 4.  I'm not seeing handles past in the mid 50s or any in the 60s.  Are you using an iGrillV2 and what firmware is on it?  I'm running firmware 1.5 on my iGrillV2 according to the Webber app.  Perhaps your firmware is newer.  Also, are you using a pi3 and the integrated Bluetooth module or a separate USB Bluetooth adapter? Any idea on how to update the firmware if you are running something else?

**Comment by bjoernhoefer** [comment]
If you're running gatttool you will see the handles.

I'm running the latest firmware - updates were installed with the weber-app.

I'm unsing the Pi3 embedded Bluetooth adapter

**Comment by ghost** [comment]
I actually don't see the same handles in gatttool that you are seeing.  I bet my V2 is about a year or two old so the firmware must be different.  When you get a chance can you post the reported firmware version from the Webber App?  I too was getting notifications on prove temps at one point in time.  Almost like it was previously paired/bonded and was subscribing to notifications on the correct handles.  (Not the same as what you have in your new code) Then for some reason they no longer worked.  Not sure if it was a power cycle or a pairing operation with the Webber app that mucked it up.  I'm afraid your solution may not be very robust.  Again the firmware version might be the key.

**Comment by ghost** [comment]
BTW, I get nothing from the Webber app allowing me to update from the 1.5 firmware version.

**Comment by bjoernhoefer** [comment]
I also have the firmware version 1.5 - i found out how to "enable" the "push" settings:
You have to set an alarm for one of the 4 probes (i set mine to 400 - which is preeety unrealistic, so the device won't start beeping in the wrong time) - and if I connect me via gatttool to the the igrill and get the values from all probes (now with handle 0x0034 for probe1, 0x0035 for probe 2....) - interesting feature - but I can live with that...

syntax for gatttool: `gatttool -I -b d4:81:ca:23:xx:xx`

I'll get an update as soon as the temperature changes - I'll get an update via bluetooth

```
[d4:81:ca:23:xx:xx][LE]> connect 
Attempting to connect to d4:81:ca:23:xx:xx
Connection successful
Notification handle = 0x0043 value: 49 00 00 
Notification handle = 0x0043 value: 4a 00 00 
Notification handle = 0x0043 value: 4b 00 00 
Notification handle = 0x0043 value: 4a 00 00 
Notification handle = 0x0043 value: 4b 00 00 
Notification handle = 0x0043 value: 4a 00 00 
Notification handle = 0x0043 value: 4b 00 00 
Notification handle = 0x0052 value: 46 
Notification handle = 0x0043 value: 4a 00 00 
Notification handle = 0x0043 value: 4b 00 00 
Notification handle = 0x0043 value: 4a 00 00 
Notification handle = 0x0043 value: 4b 00 00 
Notification handle = 0x0043 value: 4a 00 00 
Notification handle = 0x0043 value: 4b 00 00 
Notification handle = 0x0043 value: 30 f8 00 
```
If you want fast value changes just cover one connected probe with your hand - and you see the numbers flying in...

I've also power cycled the device (removed batteries) - i think after that it is necessary to set alarms newly via the Weber app - and then do a bit "troubleshooting" via gatttool - everything in an acceptable range for me... - for now..

So I would suggest, if you have any further problem/questions we should discuss this in "my" project - as this is veeery off topic here.

Also please note - as this is my first time I do something with python (and also with bluetooth) - don't except any magic - I'm an completely newbie.... (to python :-) )
Any contribution from your side is warmly welcome too ;-)

**Comment by ghost** [comment]
Ok those handle numbers make more since compare to what I'm seeing. Handle 52 is the battery in hex so you should be able to see % remaining.  At one point over the last few weeks I was getting notification like you are seeing.  Was never able to reproduce them.  I'll give the alarms a try to see if that forces the notification on those handles. Thanks for checking the firmware and I'm also a newbie to buetooth and python. Lots of reading and trial and error over the last few months.

**Comment by bjoernhoefer** [comment]
You're right - Handle 52 looks good an additional information I can push to my mqtt-environment.

I've tried is to remove all alarms which leads to silence on the gatttol...
One "strange" thing - you just have to set an alarm for one probe (in my case i've set it to 400 degrees celsius) and it sends values for any connected probe, even if the "alarming"-probe is disconnected.

**Comment by ghost** [comment]
Oh that's helpful info... I'm assuming you are setting the alarm in the Webber App.  I'll give that a go when I get home. 🙂

**Comment by bjoernhoefer** [comment]
yes sure - you first must disconnect the raspberry pi, then start the weber app, connect the igrill, configure one alarm and you're good to go...

Please note, the set alarm will also trigger a audio alarm on the igrill itself... so if you set it "wrong" during a long job you might wake up your neighbors/kids/etc.... ;-)

**Comment by ghost** [comment]
Ok now I'm getting the notifications in gattool like you are after setting the alarm.  Wow how did you figure that one out???  When I get time I'll try and run wireshark during the setting of the alarm to see if we can then fully automate the process without the need for the alarm setup within the app. Did you try and change your Main.py to match the handles we are seeing to get a python version working?

**Comment by bjoernhoefer** [comment]
I've always had some alarms set - as I like this alarm-feature very much...
Just like I said, I was googleing about some things when gatttool was connected - when the digits where suprising me :-)

I don't think the alarm settings will be so easy, as you have to authenticate yourself on the thermoter, which a found out is absolutely not working as is should... so if you'd like, go on and do it - I'm happy with my solution so far (maybe some minor improvements will get in - in the next few days as I'll find time....)

**Comment by ghost** [comment]
I probably won't spend much time auto setting the alarm.  My ultimate goal is to be able to monitor my temps from the web.  I plan on gathering the temps and hosting a web service on the PI to then relay those temps via a connected browser.  I should be able to monitor and set alarms from the web interface and then signal by email or SMS updates or alarms.  I was able tap into the uart on the pcb and feed that into the PI and parse all of the data being sent to the Bluetooth radio before any type of encryption.  This solution works but requires the PI to be out with my smoker.  The full wireless version allows me to keep the PI inside.  I was able to hook up a UART to Bluetooth module from adafruit and I got the same serial stream from the Bluetooth module.  Kind of a nice feature because you can have both the Webber app running on the original Bluetooth module and the stream from the uart to the PI.  You can even power the V2 from the PI.   Not sure if this helps with what your doing but I'd be interested in knowing you end goals.

**Comment by bjoernhoefer** [comment]
I'll keep mine outside - as I'm thinking about an video-live-stream ;-)

regarding the web-ui and alerting and so on I can really recommend [Node-Red](http://developers.sensetecnic.com/article/a-node-red-dashboard-using-node-red-dashboard/) I'm using it for my entire house... and it can do everything - and it can also run on raspberry pi if you don't have a server...

My goal is almost reached as I'm able to connect my Pi to the V2 and extract the "important" data and send them into my "infrastructure" - all other things will be done by my internal logic.

**Comment by meirkl** [comment]
> Would be nice if someone posted steps to actually get some temp readings from the iGrill V2. Here is the wireshark dump that I collected. I first went into settings on my iPad and forgot the iGrill device so it would log all the pairing and bonding stuff and make use of the encryption keys to show the encrypted traffic. I then went into the Webber app and connected the device. Some valuable info on the actual handles used and the transfer of keys for authorization. Let me know if this helps.
> 
> Remove the txt extention.
> 
> [iGrillV2 with pairing and bonding.pcap.txt](https://github.com/kvantetore/igrill/files/924347/iGrillV2.with.pairing.and.bonding.pcap.txt)

@kreienhe
How did you sniff the Bluetooth packets? On which device did you run wireshark?
