### ISSUE TITLE
Cannot connect to iGrill Mini w/ FW: 1.18

### ISSUE THREAD

**Issue by Daedilus** [kvantetore/igrill#7]
Followed instructions and all I get is
Authenticating...
encrypted device challenge: 8c2fc96624607xxxx8ce006a7c8c63c5
decrypted device challenge: 39865666d259xxxx1ff7c0273c7ea68e
Invalid device challenge

**Comment by kvantetore** [comment]
Perhaps they have updated the encryption key in the new firmware? I haven't used my iGrill for some time now, so I don't know

**Comment by Daedilus** [comment]
No, it was the code. It doesn't give the option of selecting the iGrill Mini so it automatically keeps on trying for a regular iGrill.
